Task 3
zishkaz/formal-lang-course pull request #3
Opened 2022-09-25 18:02 UTC by zishkaz

# Задача 3. Регулярные запросы для всех пар вершин

* **Мягкий дедлайн**: 25.09.2022, 23:59
* **Жёсткий дедлайн**: 28.09.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [x] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-09-26 17:46 UTC, EgorOrachyov requested changes

2022-09-26 17:46 UTC, EgorOrachyov commented on project/matrix.py
> +from pyformlang.finite_automaton import NondeterministicFiniteAutomaton, State
adjacency_matrix.py ?

2022-09-26 17:46 UTC, EgorOrachyov commented on tests/test_matrix.py
> +from pyformlang.finite_automaton import (
Переименовать после matrix.py ренейминга

2022-09-26 18:04 UTC, zishkaz commented on project/matrix.py
> +from pyformlang.finite_automaton import NondeterministicFiniteAutomaton, State
Сделано

2022-09-26 18:04 UTC, zishkaz commented on tests/test_matrix.py
> +from pyformlang.finite_automaton import (
Сделано

2022-09-27 17:43 UTC, EgorOrachyov approved these changes

2022-09-27 22:12 UTC, merged