Task 4
zishkaz/formal-lang-course pull request #4
Opened 2022-10-05 20:29 UTC by zishkaz

# Задача 4. Регулярные запросы для нескольких стартовых вершин

* **Мягкий дедлайн**: 02.10.2022, 23:59
* **Жёсткий дедлайн**: 05.10.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [x] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-10-06 08:08 UTC, EgorOrachyov requested changes

2022-10-06 08:08 UTC, EgorOrachyov commented on tests/test_rpq_bfs.py
> +    assert actual_rpq == expected_rpq
Еще бы тест кейсов пару добавить на разные regex

2022-10-06 08:08 UTC, EgorOrachyov commented on tests/test_rpq_tensor.py
> +    actual_rpq = rpq_tensor(graph, query, start_nodes, final_nodes)
Еще бы тест кейсов пару добавить на разные regex

2022-10-06 16:49 UTC, zishkaz commented on tests/test_rpq_bfs.py
> +    assert actual_rpq == expected_rpq
Сделано

2022-10-06 16:49 UTC, zishkaz commented on tests/test_rpq_tensor.py
> +    actual_rpq = rpq_tensor(graph, query, start_nodes, final_nodes)
Сделано

2022-10-07 10:58 UTC, EgorOrachyov approved these changes

2022-10-07 11:01 UTC, merged